### ISSUE TITLE
inconsistent function signature between r2ghidra and radare2

### ISSUE THREAD

**Issue by Zzorz** [radareorg/r2ghidra-dec#119]
The r2ghidra seems to have some problem when dealing with function signature, especially when it comes to the imported functions. 

To reproduce this problem, just need a simple C code:
```
#include <stdlib.h>

int main(){
        return atoi("\x0");
}
```

![image](https://user-images.githubusercontent.com/22562519/84899731-a32a3480-b0db-11ea-9164-8a5c7f93299b.png)

In this condition, the decompiler just think that atoi return void, instead of a int type.
But in ghidra, the function signature is correct:
![image](https://user-images.githubusercontent.com/22562519/84900268-6e6aad00-b0dc-11ea-9192-c3379a084dcd.png)
![image](https://user-images.githubusercontent.com/22562519/84900320-7fb3b980-b0dc-11ea-8729-84f22d9d8440.png)

**Comment by ITAYC0HEN** [comment]
Indeed this is probably because Ghidra knows the signature for atoi, or because it understood it from the context.

In radare2, it is treated as an imported function which doesn't have an hard-coded signature in the program. Moreover, analysis performed by ghidra can't be compared to the analysis by r2ghidra as there will always be differences. It need to be compared to the analysis of radare2 itself (regardless of the decompiler)
