### ISSUE TITLE
cross-compiling fails (builds sleighc for target, not host)

### ISSUE THREAD

**Issue by classabbyamp** [radareorg/r2ghidra-dec#298]
when cross-compiling, cmake builds `sleighc` for the target arch, not the host, so it isn't able to run it later on.

```
$ file masterdir/builddir/rz-ghidra/build/ghidra/sleighc
masterdir/builddir/rz-ghidra/build/ghidra/sleighc: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=fab7a1f3d871bbd3a2b645a7e85ccb50b2bfbbc1, for GNU/Linux 3.7.0, not stripped
```

abbreviated log:
```
[109/231] Generating sleigh/80390.sla
FAILED: ghidra/sleigh/80390.sla /builddir/rz-ghidra/build/ghidra/sleigh/80390.sla 
cd /builddir/rz-ghidra/ghidra/ghidra/Ghidra/Processors/8051/data/languages && sleighc /builddir/rz-ghidra/ghidra/ghidra/Ghidra/Processors/8051/data/languages/80390.slaspec /builddir/rz-ghidra/build/ghidra/sleigh/80390.sla
/bin/sh: line 1: sleighc: command not found
[110/231] Generating sleigh/80251.sla
FAILED: ghidra/sleigh/80251.sla /builddir/rz-ghidra/build/ghidra/sleigh/80251.sla 
cd /builddir/rz-ghidra/ghidra/ghidra/Ghidra/Processors/8051/data/languages && sleighc /builddir/rz-ghidra/ghidra/ghidra/Ghidra/Processors/8051/data/languages/80251.slaspec /builddir/rz-ghidra/build/ghidra/sleigh/80251.sla
/bin/sh: line 1: sleighc: command not found
[111/231] Generating sleigh/8048.sla
FAILED: ghidra/sleigh/8048.sla /builddir/rz-ghidra/build/ghidra/sleigh/8048.sla 
cd /builddir/rz-ghidra/ghidra/ghidra/Ghidra/Processors/8048/data/languages && sleighc /builddir/rz-ghidra/ghidra/ghidra/Ghidra/Processors/8048/data/languages/8048.slaspec /builddir/rz-ghidra/build/ghidra/sleigh/8048.sla
/bin/sh: line 1: sleighc: command not found
[112/231] Generating sleigh/8051.sla
FAILED: ghidra/sleigh/8051.sla /builddir/rz-ghidra/build/ghidra/sleigh/8051.sla 
cd /builddir/rz-ghidra/ghidra/ghidra/Ghidra/Processors/8051/data/languages && sleighc /builddir/rz-ghidra/ghidra/ghidra/Ghidra/Processors/8051/data/languages/8051.slaspec /builddir/rz-ghidra/build/ghidra/sleigh/8051.sla
/bin/sh: line 1: sleighc: command not found
```

**Comment by karliss** [comment]
Just checked the cmake docs for [their recommended setup of doing it](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html#running-executables-built-in-the-project) . It looked relatively simple, it would be relatively easy to accidentally create much more convoluted setup if you tried to construct it from scratch. 

There is one minor optimization that could improve the overall build speed not listed in CMake docs example. Asking build system to build only the required tool during first build instead of everything would save some time.  But that should be relatively easy to do with standard build system flags and no customization to the build system.

Only thing that might cause issues (depending on how the cross compilation setup is handled) is the part where you invoke the build twice first with native toolchain and afterwards with cross compilation. If you are doing the cross-compilation build manually or in a setup where configuration of cross-compilation toolchain for each project supports custom recipe different from normal build (assuming doing stuff at distro maintainer level).  I could imagine situation where someone is trying to force the cross-compilation by something like CC and other environment variables so that it isn't necessary  to customize build system flags for each project, in that case this the recommended setup wouldn't work as smoothly.

@classabbyamp What's your situation and setup for doing cross-compilation?  Would the setup suggested by CMake work in your situation?

**Comment by classabbyamp** [comment]
sorry for the long wait, I got busy.

turns out I wasn't setting `CMAKE_CROSSCOMPILING_EMULATOR`. setting that allows cross-compiling to work properly
