### ISSUE TITLE
radare2 failed to use r2ghidra-dec in global path

### ISSUE THREAD

**Issue by dmknght** [radareorg/r2ghidra-dec#59]
I moved data of r2ghidra-dec plugin from `.local/share/radare2/plugins/` to the global path (LIBR_PLUGINS) and i have this error:

`Ghidra Decompiler Error: No sleigh specification for x86:LE:32:default`

My global path of radare2: `R2_LIBR_PLUGINS=/usr/lib/x86_64-linux-gnu/radare2/4.1.0-git`

Data in the path: 
```
$ls
total 12M
-rwxr-xr-x 1 root root  12M Dec 13 01:41 core_ghidra.so
drwxr-xr-x 1 root root 6.6K Dec 13 01:42 r2ghidra_sleigh
```

# Full r2 -H
```
R2_PREFIX=/usr
R2_MAGICPATH=/usr/share/radare2/4.1.0-git/magic
R2_PREFIX=/usr
R2_INCDIR=/usr/include/libr
R2_LIBDIR=/usr/lib/x86_64-linux-gnu
R2_LIBEXT=so
R2_RCONFIGHOME=/home/dmknght/.config/radare2
R2_RDATAHOME=/home/dmknght/.local/share/radare2
R2_RCACHEHOME=/home/dmknght/.cache/radare2
R2_LIBR_PLUGINS=/usr/lib/x86_64-linux-gnu/radare2/4.1.0-git
R2_USER_PLUGINS=/home/dmknght/.local/share/radare2/plugins
R2_USER_ZIGNS=/home/dmknght/.local/share/radare2/zigns
```

**Comment by thestr4ng3r** [comment]
That's because the initial install patch will be baked into the plugin, so it can locate the sleigh files after being installed. You can check the final path with something like this:
```
r2 core_ghidra.so -qc "s sym.SetInitialSleighHome_r_config_t; af; pdf~str~r2ghidra"
```
Your options are the following:
* Set the path at runtime using the `SLEIGHHOME` env var or `e r2ghidra.sleighhome` (probably not what you want)
* Set `CMAKE_INSTALL_PREFIX` to your final destination prefix (in your case `/usr`) and install directly there: `cmake -DCMAKE_INSTALL_PREFIX=/my/final/destination ..`
* Set `CMAKE_INSTALL_PREFIX` like above, but then install it somewhere else and copy it later. This can be done like this: `cmake -DCMAKE_INSTALL_PREFIX=/my/final/destination .. && make && make install DESTDIR=/some/tmp/dir`. Then the plugin will be in `/some/tmp/dir/my/final/destination/share/radare2/plugins/core_ghidra.so`, but have `/my/final/destination/share/radare2/plugins/r2ghidra_sleigh` as its builtin sleigh path.

If you don't want the plugin to be in `<prefix>/share/radare2/plugins`, you can also change that like this: `cmake -DRADARE2_INSTALL_PLUGDIR=lib/x86_64-linux-gnu/radare2/4.1.0-git`. The same applies for the cutter path with `CUTTER_INSTALL_PLUGDIR`.

**Comment by dmknght** [comment]
Solved! the `-DRADARE2_INSTALL_PLUGDIR=` must be set `/usr/lib/x86_64-linux-gnu/radare2/4.1.0-git` and set the `-DCMAKE_INSTALL_PREFIX=` to `/usr/`  (this match cutter plugin)
